import {decorativePath, samplesPath, AUDIO_FIXTURE} from './wave.js';
import {enhanceButton} from '../materiality-behavior/button.js';
const $ = s => document.querySelector(s), svgNS = 'http://www.w3.org/2000/svg';
const conditions = [['A','波形なし','基準'],['B','静的な波形','表面 / 装飾'],['C','操作に反応','入力反応'],['D','状態・データに対応','意味を対応付ける']];
const sampleNotes = {button:'同じ「保存する」を比較。保存は模擬受付です。Dだけ、この画面で受け付けた操作の間隔を計測します。',status:'模擬処理です。サーバーの実際の進捗ではありません。進捗・完了・エラーはすべて文字でも表示します。',audio:'模擬音声です。マイクへのアクセス・録音・音声出力はありません。24個の固定テスト値を125ms間隔で順に表示します。'};
let sample = new URL(location).searchParams.get('sample') || 'button'; if (!(sample in sampleNotes)) sample='button';
$('#sample').value=sample;
const rm = matchMedia('(prefers-reduced-motion: reduce)');
const motionAllowed = () => !rm.matches && !$('#motion-off').checked && !document.hidden;
const states = [], waves = new Map(); let frame = 0, lastFrame = 0;
const params = () => Object.fromEntries(['amplitude','cycles','decay','speed','style'].map(id => [id,id==='style'?$('#'+id).value:Number($('#'+id).value)]));
function svg(id, meaningful=false) {return `<svg class="wave" viewBox="0 0 240 80" ${meaningful?`role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">波形</title><desc id="${id}-desc">値は以下の表でも確認できます。</desc>`:'aria-hidden="true">'}<line class="axis" x1="14" y1="40" x2="226" y2="40"/><path d=""/><circle class="data-point" cx="14" cy="40" r="3" hidden/><line class="cursor" x1="14" y1="12" x2="14" y2="68" hidden/></svg>`;}
function startWave(s) {if(s.condition!=='C'||!motionAllowed())return;waves.set(s,{started:performance.now()});schedule();}
function clearWave(s){waves.delete(s);s.reactive?.querySelector('path').setAttribute('d','M14,40 L226,40');}
function schedule(){if(!frame&&waves.size)frame=requestAnimationFrame(animate);}
function animate(now){frame=0;if(!motionAllowed()){stopWaves();return;}if(now-lastFrame>=33){lastFrame=now;const p=params();for(const [s,w] of waves){const elapsed=(now-w.started)/1000;if(elapsed>1/p.speed||s.type!==sample||s.article.hidden){clearWave(s);continue;}s.reactive.querySelector('path').setAttribute('d',decorativePath({...p,phase:elapsed*6,travel:elapsed*p.speed,decay:elapsed*p.decay}));}}schedule();}
function stopWaves(){for(const s of [...waves.keys()])clearWave(s);if(frame)cancelAnimationFrame(frame);frame=0;}
function result(s,text){s.result.textContent=text;}
function table(s, headings, rows){s.table.replaceChildren();const tr=document.createElement('tr');for(const heading of headings){const th=document.createElement('th');th.scope='col';th.textContent=heading;tr.append(th);}const head=document.createElement('thead');head.append(tr);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const cell of row){const td=document.createElement('td');td.textContent=String(cell);tr.append(td);}body.append(tr);}s.table.append(head,body);}
function dataChart(s,values,min,max,title,description){s.chart.querySelector('path').setAttribute('d',samplesPath(values,{min,max}));const point=s.chart.querySelector('.data-point');point.toggleAttribute('hidden',values.length!==1);if(values.length===1){point.setAttribute('cx','14');point.setAttribute('cy',String(66-(values[0]-min)/(max-min)*52));}s.chart.querySelector('title').textContent=title;s.chart.querySelector('desc').textContent=description;s.article.querySelector('.chart-title').textContent=title;}
function decorate(){const p=params();for(const s of states)if(s.condition==='B')s.article.querySelector('.decorative path').setAttribute('d',decorativePath({...p,decay:0}));}
function addCard(type,[condition,title,role]){
 const id=`${type}-${condition}`;const article=document.createElement('article');article.className='card';article.dataset.type=type;article.dataset.condition=condition;article.id=id;
 const button=type==='button';
 article.innerHTML=`<div class="condition"><b>${condition}</b><span class="tag">${role}</span></div><h3>${title}</h3><p class="source">${condition==='B'?'生成した装飾線。計測値・処理状況ではありません。':condition==='C'?'入力に対する演出。処理完了の合図ではありません。':condition==='D'?(button?'データ源：この画面の受付時刻の差。':'audio'===type?'データ源：固定の模擬信号。実測ではありません。':'模擬進捗・状態を波形へ対応付けます。'):'波形を使わず、同じ結果を伝えます。'}</p><div class="stage">${button?`<button type="button" class="andm-btn wave-button" id="${id}-action">${['B','C'].includes(condition)?svg(id):''}<span>保存する</span></button>`:condition==='B'||condition==='C'?svg(id):'<span class="empty">波形の装飾なし</span>'}</div>${!button?`<p class="step" aria-live="off">${type==='status'?'進捗：0 / 20':'サンプル：0 / 24、現在値：—'}</p>${type==='status'?'<progress max="20" value="0" aria-label="模擬処理の進捗"></progress>':''}<div class="actions"><button class="andm-btn andm-btn--filled start" type="button">${type==='status'?'模擬処理を開始':'模擬入力を開始'}</button><button class="andm-btn andm-btn--outlined pause" disabled type="button">一時停止</button><button class="andm-btn andm-btn--outlined stop" disabled type="button">中止</button>${type==='status'?'<button class="andm-btn andm-btn--outlined complete" disabled>完了にする</button><button class="andm-btn andm-btn--outlined error" disabled>エラーにする</button>':''}</div>`:''}<p class="result" role="status">${button?'まだ受け付けていません。':'開始すると状態を表示します。'}</p>${button?`<label><input class="disable" type="checkbox"> このButtonを無効にする</label>`:''}${condition==='D'?`<div class="chart"><p class="chart-title">${button?'受付間隔 / ms':type==='audio'?'模擬振幅 / −1〜1':'残りの模擬作業量 / 0〜20'}</p>${svg(id+'-chart',true)}<p class="source">${button?'横：受付した順。縦：間隔ms（0〜表の最大値）。最初の操作は間隔なし。':type==='audio'?'横：0〜2875ms。縦：正規化したテスト振幅−1〜1。カーソルは表示中のサンプル。':'横：模擬操作の進行履歴。縦：残りの作業量。完了は0、エラーは波を止め文字で区別。'}</p><details><summary>数値表を見る</summary><table><caption>${button?'受付間隔の履歴':type==='audio'?'固定テスト信号（測定値ではありません）':'模擬作業量の履歴'}</caption></table></details></div>`:''}`;
 $('#cards').append(article);
 const s={type,condition,article,result:article.querySelector('.result'),chart:article.querySelector('.chart .wave'),table:article.querySelector('table'),reactive:condition==='C'?article.querySelector('.wave'):null,count:0,times:[],values:[],step:0,phase:'idle',timer:null,paused:false};states.push(s);
 if(condition==='B')article.querySelector('.wave').classList.add('decorative');
 if(button){const native=article.querySelector('.wave-button');s.controller=enhanceButton(native,{onState(state){if(state==='press')startWave(s);if(state==='cancel')clearWave(s);},onConfirm({at}){if(s.condition==='C'&&!waves.has(s))startWave(s);s.count++;if(s.times.length)s.values.push(Math.round(at-s.times.at(-1)));s.times.push(at);s.values=s.values.slice(-8);result(s,`模擬保存を受け付けました。${s.count}回。復元を待たず受付。`);if(condition==='D'){dataChart(s,s.values,0,Math.max(1,...s.values),'受付間隔 / ms','この画面の操作間隔です。数値表に同じ値があります。');table(s,['間隔の順','ms'],s.values.map((v,i)=>[i+1,v]));}}});article.querySelector('.disable').addEventListener('change',e=>{native.disabled=e.target.checked;clearWave(s);});}
 else {article.querySelector('.start').addEventListener('click',()=>{clearInterval(s.timer);s.step=0;s.values=s.type==='status'?[20]:[];s.paused=false;s.phase='running';startWave(s);result(s,type==='audio'?'模擬入力を開始しました。録音はしていません。':'模擬処理を開始しました。');update(s);run(s);});article.querySelector('.pause').addEventListener('click',()=>{s.paused=!s.paused;clearInterval(s.timer);stopWaves();result(s,s.paused?'一時停止しました。':type==='audio'?'模擬入力を再開しました。':'模擬処理を再開しました。');update(s);if(!s.paused)run(s);});article.querySelector('.stop').addEventListener('click',()=>finish(s,'cancelled'));article.querySelector('.complete')?.addEventListener('click',()=>{s.step=20;s.values.push(0);finish(s,'complete');});article.querySelector('.error')?.addEventListener('click',()=>finish(s,'error'));
 if(condition==='D'&&type==='audio'){dataChart(s,[...AUDIO_FIXTURE],-1,1,'固定模擬信号 / 振幅−1〜1','固定24サンプルの折れ線。実際の音声入力ではありません。');table(s,['時間 / ms','模擬振幅'],AUDIO_FIXTURE.map((v,i)=>[i*125,v]));}if(condition==='D'&&type==='status'){s.values=[20];drawStatus(s);}}
}
function drawStatus(s){if(s.condition!=='D')return;dataChart(s,s.values,0,20,'残りの模擬作業量 / 0〜20',`模擬状態：${s.phase}。形ではなく文字の状態も参照してください。`);table(s,['更新順','残り'],s.values.map((v,i)=>[i,v]));}
function update(s){s.article.querySelector('.step').textContent=s.type==='status'?`進捗：${s.step} / 20`:`サンプル：${s.step} / 24、現在値：${s.step?AUDIO_FIXTURE[s.step-1]:'—'}`;s.article.querySelector('progress')?.setAttribute('value',String(s.step));const running=s.phase==='running';for(const cls of ['pause','stop','complete','error']){const b=s.article.querySelector('.'+cls);if(b)b.disabled=!running;}s.article.querySelector('.pause').textContent=s.paused?'再開':'一時停止';if(s.type==='status')drawStatus(s);else if(s.condition==='D'){const cursor=s.chart.querySelector('.cursor');cursor.toggleAttribute('hidden',!s.step);const x=14+Math.max(0,s.step-1)/23*212;cursor.setAttribute('x1',x);cursor.setAttribute('x2',x);}}
function run(s){if(document.hidden||s.type!==sample||s.article.hidden)return;s.timer=setInterval(()=>{s.step++;if(s.type==='status')s.values.push(20-s.step);update(s);if(s.step>=(s.type==='status'?20:24))finish(s,'complete');},s.type==='status'?200:125);}
function finish(s,phase){clearInterval(s.timer);s.timer=null;s.phase=phase;s.paused=false;clearWave(s);update(s);result(s,phase==='complete'?(s.type==='audio'?'模擬入力が終了しました。録音はしていません。':'模擬処理が完了しました。'):phase==='error'?'模擬エラーです。処理結果を確認してください。':'中止しました。未完了です。');}
function visible(){stopWaves();const view=$('#view').value;$('#cards').classList.toggle('single',view!=='all');for(const s of states){clearInterval(s.timer);s.timer=null;s.article.hidden=s.type!==sample||(view!=='all'&&view!==s.condition);if(!s.article.hidden&&s.phase==='running'&&!s.paused)run(s);}$('#sample-note').textContent=sampleNotes[sample];const url=new URL(location);url.searchParams.set('sample',sample);url.searchParams.set('view',view);history.replaceState(null,'',url);}
function motionNote(){stopWaves();$('#motion-note').textContent=rm.matches?'OSのReduced Motionに従い、入力の波は静止。状態とデータの更新は維持します。':$('#motion-off').checked?'演出を停止しました。操作と文字・データは維持します。':'操作時だけ動きます。自動開始しません。';}
for(const type of ['button','status','audio'])for(const c of conditions)addCard(type,c);
const initialView=new URL(location).searchParams.get('view');if(['A','B','C','D'].includes(initialView))$('#view').value=initialView;
$('#sample').addEventListener('change',e=>{sample=e.target.value;visible();});$('#view').addEventListener('change',visible);
for(const id of ['amplitude','cycles','decay','speed','style'])$('#'+id).addEventListener('input',e=>{const out=document.querySelector(`output[for=${id}]`);if(out)out.value=e.target.value;decorate();});
$('#motion-off').addEventListener('change',motionNote);rm.addEventListener('change',motionNote);
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopWaves();for(const s of states)clearInterval(s.timer);}else visible();});window.addEventListener('pagehide',()=>{stopWaves();for(const s of states)clearInterval(s.timer);});window.addEventListener('blur',stopWaves);
$('#export').addEventListener('click',()=>{const record={study:'waveform-expression-v1',recommended:null,adoption:null,sample,view:$('#view').value,decorativeParameters:params(),reducedMotion:rm.matches,motionOff:$('#motion-off').checked,notes:$('#notes').value,dataSources:{button:'local accepted-input intervals / ms',status:'simulated work / 20 steps',audio:'fixed fixture / 125ms per sample, not microphone'},audioFixture:AUDIO_FIXTURE,conditions:states.map(s=>({sample:s.type,condition:s.condition,count:s.count,intervals:s.type==='button'?s.values:undefined,step:s.step,phase:s.phase}))};const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='waveform-observation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#export-status').textContent='観察JSONを保存しました。採用判断は未設定です。';});
decorate();visible();motionNote();
