/* Gallery のシリーズ名と「動き」の説明。色や duration のトークン値は書かない。 */
(function (root) {
  root.ANDM_SERIES_COPY = {
    order: [
      "baseline",
      "soft",
      "dense",
      "technical",
      "editorial",
      "playful",
      "expressive",
      "dads",
      "apple",
      "spectrum",
      "fluent",
      "carbon",
    ],
    labels: {
      baseline: "Baseline",
      soft: "Soft",
      dense: "Dense",
      technical: "Technical",
      editorial: "Editorial",
      playful: "Playful",
      expressive: "M3 Expressive",
      dads: "DADS",
      apple: "Apple",
      spectrum: "Spectrum",
      fluent: "Fluent 2",
      carbon: "Carbon",
    },
    briefs: {
      baseline: {
        trait: "角も余白も中くらいで、色は強く出しません。",
        use: "どの画面にも置きやすい、中立な出発点です。",
        motion: "ホバーは色。押すと縮む。角は変えない。",
      },
      soft: {
        trait: "角は大きめ、余白はゆったり、影は薄いです。",
        use: "設定や案内など、落ち着いた画面に向きます。",
        motion: "ホバーは色。押すと少し縮む。専用の速度はない。",
      },
      dense: {
        trait: "高さを抑え、余白と文字を詰めます。",
        use: "表やツールバーなど、情報の多い画面に向きます。",
        motion: "ホバーは色。押すと少し縮む。専用の速度はない。",
      },
      technical: {
        trait: "角はほぼ直角で、等幅、影はありません。",
        use: "開発ツールやログなど、境界をはっきりさせたい画面に向きます。",
        motion: "ホバーは色。押しても縮まない。専用の速度はない。",
      },
      editorial: {
        trait: "角はなく、セリフ体で、字間を少し開けます。",
        use: "記事や読み物の末尾に向きます。",
        motion: "ホバーは色。押しても縮まない。専用の速度はない。",
      },
      playful: {
        trait: "丸く、ティールで、押したときの縮みが少し大きいです。",
        use: "はじめての操作や、気軽な招待に向きます。",
        motion: "速度は共有のまま。ホバーは色。押すと Baseline より大きく縮む。角は変えない。",
      },
      expressive: {
        trait: "ラベル付きは横長の pill です。押すと角が立ち、大きさでも強調します。",
        use: "印象を残したい、利用者向けの画面に向きます。",
        motion: "ホバーは色だけ。横長の pill のまま、押すと角が変わる。縮まない。",
      },
      dads: {
        trait: "濃い青、控えめな角、太めの字です。",
        use: "行政や公共の手続きで、迷わず押してほしい画面に向きます。",
        motion: "出典に duration がないので、速度は差し替えない。ホバーは色。押しても縮まない。",
      },
      apple: {
        trait: "システムフォントだけです。色や寸法は公式の値を入れていません。",
        use: "案内や設定など、Apple の画面に近づけたいときに向きます。",
        motion: "公式の duration は official value not specified。ホバーは色。押すと縮む。速度は共有トークンのまま。",
      },
      spectrum: {
        trait: "青の塗り、角は高さの半分、境界は 2px です。",
        use: "業務画面に向きます。境界ははっきりさせ、余白は詰めすぎません。",
        motion: "ホバーと押下は色。縮みと角の変化はない。速度は Token を見る。",
      },
      fluent: {
        trait: "ボタンの角は 4px、大きいボタンは 8px です。",
        use: "いつもの操作で、作業に集中する画面に向きます。",
        motion: "出典に duration がないので、速度は差し替えない。ホバーは色。押すと共有の縮み。角は変えない。",
      },
      carbon: {
        trait: "角は直角で、主操作は青です。高さは 32、40、48px です。",
        use: "製品の画面で、主操作を青で示したいときに向きます。",
        motion: "ホバーと押下は色。縮みと角の変化はない。速度は Token を見る。",
      },
    },
    meta: {
      baseline: {
        character: "中立に応答する",
        sourceKind: "andm",
        sourceNote: "andm の出発点。特定の公式体系ではない。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式の Design System ではない。",
        interpretation: "角も余白も中くらいで、色は強く出さない。Button は共通クラスのまま。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      soft: {
        character: "ゆるく応答する",
        sourceKind: "andm",
        sourceNote: "andm の Series。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式の Reference ではない。",
        interpretation: "角は大きめ、余白はゆったり、影は薄い。必ず lift、とはしない。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      dense: {
        character: "詰めて応答する",
        sourceKind: "andm",
        sourceNote: "andm の Series。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式の Reference ではない。",
        interpretation: "高さと余白と文字を詰める。Density の Global Token にはしていない。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      technical: {
        character: "境界をはっきりさせる",
        sourceKind: "andm",
        sourceNote: "andm の Series。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式の Reference ではない。",
        interpretation: "角はほぼ直角、等幅、影はない。押しても縮まない。",
        patterns: [{ trigger: "hover", effect: "highlight" }],
      },
      editorial: {
        character: "静かに読む",
        sourceKind: "andm",
        sourceNote: "andm の Series。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式の Reference ではない。",
        interpretation: "角はなく、セリフ体。押しても縮まない。",
        patterns: [{ trigger: "hover", effect: "highlight" }],
      },
      playful: {
        character: "physical",
        sourceKind: "andm",
        sourceNote: "andm の Series。公式の Reference ではない。",
        verification: "verified",
        duration: "速度トークンは差し替えない",
        official: "公式情報は無い。",
        interpretation: "press の compress を Baseline より大きい縮みとして置ける。必ず lift、とはしない。今の解釈では morph に向かわない。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      expressive: {
        character: "形と色の応答を分ける",
        sourceKind: "official",
        sourceNote: "Material Design 3 の motion specs と buttons。曲線の数値は Token を見る。",
        verification: "verified",
        duration: "形と色で Expressive の既存トークンを使う。short1–short4 には詰めない",
        official: "押下で角が変わる。fast spatial と fast effects は公式の曲線。spring の生の stiffness はここには書かない。",
        interpretation: "press は morph に向かい、scale は 1。hover で角は変えない。lift は必須にしない。押下中に半径 0 は経由しない。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "morph" },
        ],
      },
      dads: {
        character: "迷わず押せる",
        sourceKind: "official",
        sourceNote: "デジタル庁デザインシステムの公開情報の解釈。公式ファイルは同梱しない。",
        verification: "verified",
        duration: "official value not specified",
        official: "モーションの duration は本文に無い。",
        interpretation: "速度トークンは差し替えない。ホバーは色。押しても縮まない。",
        patterns: [{ trigger: "hover", effect: "highlight" }],
      },
      apple: {
        character: "共有トークンのまま応答する",
        sourceKind: "official",
        sourceNote: "Human Interface Guidelines。duration の数値は本文に無い。",
        verification: "verified",
        duration: "official value not specified",
        official: "HIG の motion には考え方がある。duration も cubic-bezier も本文に無い。",
        interpretation: "速度トークンは差し替えない。press の scale は Baseline のままで、HIG の測定値ではない。シリーズ差はシステムフォントだけ。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      spectrum: {
        character: "色で応答する",
        sourceKind: "official",
        sourceNote: "Spectrum 2 の公開トークン。数値は Token を見る。",
        verification: "verified",
        duration: "出典の duration を short1 / short2 に写している",
        official: "ホバーと押下は色。縮みと角の変化は無い。",
        interpretation: "Express は使わない。角は高さの半分。境界はボタンの仕様。",
        patterns: [{ trigger: "hover", effect: "highlight" }],
      },
      fluent: {
        character: "慣れた操作のまま",
        sourceKind: "official",
        sourceNote: "Fluent 2 の shapes と typography。duration は本文に無かった。",
        verification: "verified",
        duration: "official value not specified",
        official: "ボタンの角は本文の shapes。duration の数値は無い。",
        interpretation: "速度トークンは差し替えない。押すと共有の縮み。角は変えない。",
        patterns: [
          { trigger: "hover", effect: "highlight" },
          { trigger: "press", effect: "compress" },
        ],
      },
      carbon: {
        character: "色で応答する",
        sourceKind: "official",
        sourceNote: "Carbon の white テーマと motion。数値は Token を見る。",
        verification: "verified",
        duration: "出典の duration を short1 / short2 に写している",
        official: "ホバーと押下は色。角は変えない。",
        interpretation: "角は 0 のまま。押下の縮小はしない。",
        patterns: [{ trigger: "hover", effect: "highlight" }],
      },
    },
  };
})(typeof globalThis !== "undefined" ? globalThis : window);
