import {scope,emit,status,text} from './shared.js';
const iso=d=>d.toISOString().slice(0,10),date=s=>new Date(s+'T12:00:00Z');
const isDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(date(s).getTime())&&iso(date(s))===s;
export function calendar(root,{value='',range=false,min='',max=''}={}){if((value&&!isDate(value))||(min&&!isDate(min))||(max&&!isDate(max))||(min&&max&&min>max))throw new TypeError('Invalid calendar date or bounds');const life=scope(),body=root.querySelector('tbody'),title=root.querySelector('[data-month]');let selected=value?[value]:[],focused=value||iso(new Date()),month=date(focused);month.setUTCDate(1);
 function valid(s){return (!min||s>=min)&&(!max||s<=max);}
 function draw(move=false){title.textContent=month.getUTCFullYear()+'年'+(month.getUTCMonth()+1)+'月';body.replaceChildren();const first=month.getUTCDay(),days=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,0)).getUTCDate();let row;
 for(let i=0;i<Math.ceil((days+first)/7)*7;i++){if(i%7===0){row=document.createElement('tr');row.setAttribute('role','row');body.append(row);}const cell=document.createElement('td');cell.setAttribute('role','gridcell');row.append(cell);const n=i-first+1;if(n<1||n>days)continue;const d=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth(),n,12)),s=iso(d),b=text('button',n);b.type='button';b.dataset.day=s;b.disabled=!valid(s);b.tabIndex=s===focused?0:-1;b.setAttribute('aria-label',new Intl.DateTimeFormat('ja-JP',{dateStyle:'full',timeZone:'UTC'}).format(d));cell.setAttribute('aria-selected',String(selected.includes(s)));if(selected.length===2&&s>=selected[0]&&s<=selected[1])cell.dataset.inRange='true';if(s===iso(new Date()))b.setAttribute('aria-current','date');b.addEventListener('click',()=>choose(s));b.addEventListener('keydown',e=>key(e,s));cell.append(b);}
 const target=root.querySelector('[data-day="'+focused+'"]');if(!target){const first=root.querySelector('[data-day]:not(:disabled)');if(first){focused=first.dataset.day;first.tabIndex=0;}}if(move)root.querySelector('[data-day="'+focused+'"]')?.focus();}
 function choose(s){if(!valid(s))return;focused=s;selected=range?(selected.length!==1?[s]:[selected[0],s].sort()):[s];draw(true);status(root,range?(selected.length===1?'開始日 '+s+'。終了日を選んでください':selected[0]+'から'+selected[1]):s+'を選択しました');emit(root,'andm:change',{value:range?selected.slice():s});}
 function key(e,s){if(e.isComposing)return;const d=date(s);if(e.key==='ArrowRight')d.setUTCDate(d.getUTCDate()+1);else if(e.key==='ArrowLeft')d.setUTCDate(d.getUTCDate()-1);else if(e.key==='ArrowDown')d.setUTCDate(d.getUTCDate()+7);else if(e.key==='ArrowUp')d.setUTCDate(d.getUTCDate()-7);else if(e.key==='Home')d.setUTCDate(d.getUTCDate()-d.getUTCDay());else if(e.key==='End')d.setUTCDate(d.getUTCDate()+6-d.getUTCDay());else if(e.key==='PageUp'||e.key==='PageDown'){const original=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+(e.key==='PageDown'?1:-1)*(e.shiftKey?12:1));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(original,last));}else return;e.preventDefault();const next=iso(d);if(!valid(next))return;focused=next;month=date(next);month.setUTCDate(1);draw(true);}
 for(const [selector,delta] of [['[data-prev-month]',-1],['[data-next-month]',1]])life.on(root.querySelector(selector),'click',()=>{month.setUTCMonth(month.getUTCMonth()+delta);focused=iso(month);draw();});draw();return {getValue:()=>range?selected.slice():selected[0]||'',setValue(next){const values=(Array.isArray(next)?next:[next]).filter(Boolean);if(values.length>(range?2:1)||values.some(s=>!isDate(s)||!valid(s)))throw new TypeError('Invalid calendar value');selected=values.sort();focused=selected[0]||iso(new Date());month=date(focused);month.setUTCDate(1);draw();},destroy(){life.destroy();body.replaceChildren();}};
}
