import {scope,emit,status,text} from './shared.js';
let sequence=0;
export function combobox(root,{items=[],multiple=false,name='',allowCustom=false}={}){
 const life=scope(),input=root.querySelector('input:not([type=hidden])'),list=root.querySelector('[role=listbox]'),tags=root.querySelector('[data-tags]');
 if(!input||!list)throw new Error('Combobox requires input and listbox');
 const uid='andm-combo-'+(++sequence);list.id||=uid+'-list';input.setAttribute('role','combobox');input.setAttribute('aria-controls',list.id);input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');list.hidden=true;
 let options=[],active=-1,selected=[],composing=false;
 const formName=name||input.name;const valuesHost=document.createElement('span');valuesHost.hidden=true;root.append(valuesHost);if(formName)input.removeAttribute('name');
 function close(){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;}
 function sync(){valuesHost.replaceChildren();selected.forEach(item=>{const h=document.createElement('input');h.type='hidden';h.name=formName;h.value=item.value;valuesHost.append(h);});if(tags){tags.replaceChildren();selected.forEach(item=>{const tag=text('span',item.label);tag.className='andm-tag';const remove=text('button','×');remove.type='button';remove.setAttribute('aria-label',item.label+'を削除');remove.addEventListener('click',()=>{const i=selected.findIndex(x=>x.value===item.value);selected.splice(i,1);sync();emit(root,'andm:change',{values:selected.map(x=>x.value)});status(root,item.label+'を削除しました');input.focus();});tag.append(remove);tags.append(tag);});}input.setCustomValidity('');}
 function highlight(index){active=index;options.forEach((x,i)=>x.node.setAttribute('aria-selected',String(i===index)));if(options[index]){input.setAttribute('aria-activedescendant',options[index].node.id);options[index].node.scrollIntoView({block:'nearest'});}else input.removeAttribute('aria-activedescendant');}
 function render(){const q=input.value.toLocaleLowerCase();list.replaceChildren();options=[];items.filter(item=>!item.disabled&&!selected.some(s=>multiple&&s.value===item.value)&&item.label.toLocaleLowerCase().includes(q)).forEach((item,i)=>{const node=text('li',item.label);node.id=uid+'-'+i;node.setAttribute('role','option');node.setAttribute('aria-selected','false');node.addEventListener('pointerdown',e=>e.preventDefault());node.addEventListener('click',()=>choose(item));list.append(node);options.push({item,node});});if(!options.length){const empty=text('li','候補がありません');empty.setAttribute('role','presentation');list.append(empty);}list.hidden=false;input.setAttribute('aria-expanded','true');highlight(-1);status(root,options.length+'件の候補');}
 function choose(item){selected=multiple?[...selected,item]:[item];input.value=multiple?'':item.label;sync();close();emit(root,'andm:change',{value:multiple?selected.map(x=>x.value):item.value,values:selected.map(x=>x.value)});status(root,item.label+'を選択しました');input.focus();}
 life.on(input,'compositionstart',()=>composing=true);life.on(input,'compositionend',()=>{composing=false;render();});life.on(input,'input',()=>{input.setCustomValidity('');if(!multiple){selected=[];sync();}if(!composing)render();});
 life.on(input,'keydown',e=>{if(e.isComposing||composing)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)render();if(options.length)highlight((active+(e.key==='ArrowDown'?1:-1)+options.length)%options.length);}else if(e.key==='Enter'&&!list.hidden&&active>=0){e.preventDefault();choose(options[active].item);}else if(e.key==='Escape'){e.preventDefault();close();}else if(e.key==='Tab')close();else if(e.key==='Backspace'&&multiple&&!input.value&&selected.length){selected.pop();sync();emit(root,'andm:change',{values:selected.map(x=>x.value)});}});
 life.on(input,'blur',()=>{close();if(!multiple&&!allowCustom&&input.value&&!selected.some(s=>s.label===input.value))input.setCustomValidity('候補から選択してください。');if(allowCustom&&input.value){selected=[{value:input.value,label:input.value}];sync();}});
 if(input.form)life.on(input.form,'submit',()=>{if(!multiple&&!allowCustom&&input.value&&!selected.some(s=>s.label===input.value))input.setCustomValidity('候補から選択してください。');});
 if(input.form)life.on(input.form,'reset',()=>queueMicrotask(()=>{selected=[];input.value='';sync();close();}));
 return {getValue:()=>multiple?selected.map(x=>x.value):selected[0]?.value||'',setItems(next){items=next;close();},destroy(){life.destroy();close();valuesHost.remove();if(formName)input.name=formName;}};
}
