import * as ui from '../../dist/behavior/index.js';
const $=id=>document.getElementById('cc-'+id),on=(el,event,fn)=>el?.addEventListener(event,fn),say=(root,message)=>{const live=root?.querySelector('[data-status]');if(live)live.textContent=message;};
// These are explicit application examples. CSS never initializes behavior automatically.
const cities=['東京','大阪','京都','横浜','福岡'].map(label=>({value:label,label})),people=['宮本','佐藤','田中'].map(label=>({value:label,label}));
document.querySelectorAll('[data-combo]').forEach(root=>ui.combobox(root,{multiple:root.dataset.combo==='true',items:root.dataset.combo==='true'?people:cities}));
if($('count-input'))ui.characterCount($('count-input'),$('count'),{max:100});
if($('range'))ui.range($('range'));
if($('form'))ui.form($('form'),{submit:async(data,signal)=>{await pause(500,signal);if($('fail-save').checked)throw Error('simulated failure');}});
function pause(ms,signal){return new Promise((resolve,reject)=>{if(signal.aborted)return reject(new DOMException('Aborted','AbortError'));const timer=setTimeout(resolve,ms);signal.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));},{once:true});});}
if($('date-entry'))on($('date-entry'),'input',()=>{const values=['year','month','day'].map(k=>$('birth-'+k).value),[y,m,d]=values.map(Number),result=new Date(Date.UTC(y,m-1,d,12));const valid=values.every(Boolean)&&result.getUTCFullYear()===y&&result.getUTCMonth()===m-1&&result.getUTCDate()===d&&y>=1900&&y<=2100;$('birth-day').setCustomValidity(values.some(Boolean)&&!valid?'存在する年月日を入力してください':'');say($('date-entry'),valid?y+'年'+m+'月'+d+'日':values.some(Boolean)?'年月日を確認してください':'');});
on($('postcode'),'blur',()=>{const input=$('postcode'),digits=input.value.normalize('NFKC').replace(/[-\s]/g,'');const valid=!input.value||/^\d{7}$/.test(digits);input.setCustomValidity(valid?'':'7桁の数字を入力してください');input.setAttribute('aria-invalid',String(!valid));if(valid&&digits)input.value=digits.slice(0,3)+'-'+digits.slice(3);});
document.querySelectorAll('[data-calendar]').forEach(root=>{const cal=ui.calendar(root,{range:root.dataset.calendar==='true'});if(root.id==='cc-calendar'){const picker=$('calendar-dialog');ui.dialog(picker,$('calendar-open'));on($('calendar-open'),'click',()=>{if($('date-value').value)cal.setValue($('date-value').value);root.querySelector('[data-day][tabindex="0"]')?.focus();});on(root,'andm:change',e=>{$('date-value').value=e.detail.value;$('calendar-open').setAttribute('aria-label',e.detail.value+'の日付を変更');picker.close();});}else on(root,'andm:change',e=>$('range-value').textContent=e.detail.value.join(' ～ '));});
if($('tree')){ui.tree($('tree'));on($('tree'),'andm:change',e=>say($('tree').parentElement,document.getElementById(e.detail.id).textContent+'を選択しました'));}if($('treegrid'))ui.tree($('treegrid'),{grid:true});
if($('upload'))ui.upload($('upload'),{accept:['.txt','text/plain'],upload:async(file,{signal,onProgress})=>{for(let i=1;i<=4;i++){await pause(150,signal);onProgress(i*25);}if($('upload-fail').checked)throw Error('simulated failure');}});
let step=0;function stepDraw(){const root=$('stepper');root.querySelectorAll('li').forEach((item,i)=>{if(i===step)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current');item.dataset.complete=String(i<step);});root.querySelector('[data-step-back]').disabled=step===0;root.querySelector('[data-step-next]').disabled=step===2;root.querySelector('[data-step-body]').textContent=['入力の段階','内容を確認する段階','完了の段階'][step];say(root,(step+1)+'番目の段階');}if($('stepper')){on($('stepper').querySelector('[data-step-back]'),'click',()=>{step--;stepDraw();});on($('stepper').querySelector('[data-step-next]'),'click',()=>{step++;stepDraw();});}
document.querySelectorAll('[data-remove]').forEach(button=>on(button,'click',()=>{const tag=button.closest('.andm-tag'),parent=tag.parentElement;tag.remove();const target=parent.querySelector('button')||parent.closest('section').querySelector('h2');if(target){if(!target.matches('button'))target.tabIndex=-1;target.focus();}say(parent.parentElement,'タグを削除しました');}));
on(document.querySelector('[data-banner-dismiss]'),'click',()=>{$('banner').hidden=true;$('banner-show').focus();});on($('banner-show'),'click',()=>{$('banner').hidden=false;});
if($('page-nav'))$('page-nav').querySelectorAll('a').forEach(a=>on(a,'click',e=>{e.preventDefault();const target=document.querySelector(a.getAttribute('href'));target.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});target.focus({preventScroll:true});$('page-nav').querySelectorAll('a').forEach(x=>x.removeAttribute('aria-current'));a.setAttribute('aria-current','location');}));on($('scroll-top'),'click',()=>{$('section-one').scrollIntoView({block:'start'});$('section-one').focus({preventScroll:true});});
if($('mega'))ui.popover($('mega'),$('mega-trigger'));
on($('language'),'change',()=>{$('language-copy').lang=$('language').value;$('language-copy').textContent=$('language').value==='ja'?'選択した言語：日本語':'Selected language: English';});
if($('carousel'))ui.carousel($('carousel'));if($('people-dialog'))ui.dialog($('people-dialog'),$('people-open'));if($('info'))ui.popover($('info'),$('info-open'));
if($('edit'))ui.inlineEdit($('edit'),{save:async(value,signal)=>{await pause(400,signal);if($('edit-fail').checked)throw Error('simulated failure');return value;}});
on(document.querySelector('[data-reply]'),'click',()=>{$('comment-text').value='@宮本 ';$('comment-text').focus();});on($('comment-form'),'submit',e=>{e.preventDefault();const input=$('comment-text');if(!input.reportValidity())return;const article=document.createElement('article');article.className='andm-comment';const author=document.createElement('strong');author.textContent='自分';const message=document.createElement('p');message.textContent=input.value;const remove=document.createElement('button');remove.type='button';remove.className='andm-btn andm-btn--text';remove.textContent='投稿を削除';remove.addEventListener('click',()=>{article.remove();input.focus();say($('comments'),'投稿を削除しました');});article.append(author,message,remove);$('comments').querySelector('[data-posts]').append(article);input.value='';say($('comments'),'ローカルに投稿しました');});
if($('tour'))ui.tour($('tour'),$('tour-open'),{steps:[{title:'入力',description:'Nativeな入力・選択で情報を指定します。'},{title:'確認',description:'処理中と完了の違いを文字でも伝えます。'},{title:'再利用',description:'Seriesを切り替えても操作と入力は保持されます。'}]});
if($('tabs'))ui.tabs($('tabs'));for(const id of ['dialog','drawer'])if($(id))ui.dialog($(id),$(id+'-open'));if($('popover'))ui.popover($('popover'),$('popover-open'));if($('tooltip-target'))ui.tooltip($('tooltip-target'),$('tooltip'));
if($('menu')){ui.menu($('menu-open'),$('menu'));on($('menu'),'andm:action',e=>say($('menu').parentElement,e.detail.value+'を選びました'));}if($('toolbar')){ui.toolbar($('toolbar'));$('toolbar').querySelectorAll('button').forEach(b=>on(b,'click',()=>{$('toolbar').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));}
if($('task')){let timer,run=0;const root=$('task'),start=root.querySelector('[data-task-start]'),cancel=root.querySelector('[data-task-cancel]'),progress=root.querySelector('progress'),alert=root.querySelector('[data-task-alert]');on(start,'click',()=>{clearInterval(timer);const id=++run;let value=0;progress.value=0;alert.hidden=true;cancel.disabled=false;say(root,'処理中');root.setAttribute('aria-busy','true');timer=setInterval(()=>{if(id!==run)return;value+=25;progress.value=value;if(value>=100){clearInterval(timer);cancel.disabled=true;root.removeAttribute('aria-busy');alert.hidden=false;const fail=root.querySelector('[data-task-fail]').checked;alert.textContent=fail?'処理に失敗しました':'処理が完了しました';say(root,alert.textContent);}},200);});on(cancel,'click',()=>{run++;clearInterval(timer);cancel.disabled=true;root.removeAttribute('aria-busy');say(root,'中止しました');});on(window,'pagehide',()=>clearInterval(timer));}
if($('table')){const root=$('table'),rows=Array.from({length:17},(_,i)=>({id:i+1,name:'プロジェクト '+String(i+1).padStart(2,'0'),status:i%3?'進行中':'完了'}));const table=ui.dataTable(root,{rows,columns:[{key:'name'},{key:'status'}]});on(root.querySelector('[data-table-loading]'),'click',()=>table.setState('loading'));on(root.querySelector('[data-table-error]'),'click',()=>table.setState('error'));on(root.querySelector('[data-table-retry]'),'click',()=>table.setState('ready'));on(root,'andm:bulk',e=>say(root,e.detail.ids.length+'件の模擬処理を受け付けました'));}
if($('color')){const root=$('color'),hue=root.querySelector('[data-hue]'),sat=root.querySelector('[data-saturation]'),bright=root.querySelector('[data-brightness]'),picker=root.querySelector('[data-color]');function update(){const h=Number(hue.value),s=Number(sat.value)/100,v=Number(bright.value)/100;const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1))));};const hex='#'+[f(5),f(3),f(1)].map(v=>v.toString(16).padStart(2,'0')).join('');root.style.setProperty('--andm-local-hue',h);root.style.setProperty('--andm-local-color',hex);picker.value=hex;root.querySelector('[data-color-value]').textContent=hex;}for(const input of [hue,sat,bright])on(input,'input',update);on(picker,'input',()=>{root.style.setProperty('--andm-local-color',picker.value);root.querySelector('[data-color-value]').textContent=picker.value;});let dragging=false;function point(e){const box=root.querySelector('[data-plane]').getBoundingClientRect();sat.value=Math.round(Math.max(0,Math.min(1,(e.clientX-box.left)/box.width))*100);bright.value=Math.round(Math.max(0,Math.min(1,1-(e.clientY-box.top)/box.height))*100);update();}const plane=root.querySelector('[data-plane]');on(plane,'pointerdown',e=>{dragging=true;plane.setPointerCapture(e.pointerId);point(e);});on(plane,'pointermove',e=>{if(dragging)point(e);});on(plane,'pointerup',()=>dragging=false);on(plane,'pointercancel',()=>dragging=false);update();}
